---
ID: "fa5589c3-b6d8-4c28-92ae-a8e9d159da4e"
Parent: "afd4a7b3-7db6-4e8f-afae-93893a579694"
Template: "afd4a7b3-7db6-4e8f-afae-93893a579694"
Path: /sitecore/templates/Web Forms for Marketers/Assembly/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090610T150121
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
